# Generated by Django 4.2.30 on 2026-06-22 07:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionreply',
            name='is_best_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discussionreply',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_replies', to=settings.AUTH_USER_MODEL),
        ),
    ]
